exam7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

webapp/urls.py
from django.urls import path

from webapp.views.answer_views import AnswerView
from webapp.views.choice_views import PollChoiceAddView, PollChoiceUpdate, PollChoiceDelete
from webapp.views.poll_views import PollsIndexView, PollDetailView, PollAddView, PollUpdateView, PollDeleteView

urlpatterns = [
    path('', PollsIndexView.as_view(), name='index'),
    path('poll/<int:pk>/', PollDetailView.as_view(), name='poll_detail_view'),
    path('polls/add/', PollAddView.as_view(), name='poll_add'),
    path('poll/<int:pk>/update/', PollUpdateView.as_view(), name='poll_update'),
    path('poll/<int:pk>/delete/', PollDeleteView.as_view(), name='poll_delete'),
    path('poll/<int:pk>/choices/add/', PollChoiceAddView.as_view(), name='poll_choice_add'),
    path('choice/<int:pk>/update/', PollChoiceUpdate.as_view(), name='poll_choice_update'),
    path('choice/<int:pk>/delete/', PollChoiceDelete.as_view(), name='poll_choice_delete'),
    path('poll/<int:pk>/answer/', AnswerView.as_view(), name='answer_poll')
]

webapp/models.py
from django.db import models
from django.urls import reverse


class Poll(models.Model):
    question_text = models.CharField(max_length=250, verbose_name='Вопрос')
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return f'{self.question_text}'

    def get_absolute_url(self):
        return reverse('poll_detail_view', kwargs={'pk': self.pk})


class Choice(models.Model):
    choice_text = models.CharField(max_length=250, verbose_name='Вариант ответа')
    question = models.ForeignKey('webapp.Poll', on_delete=models.CASCADE, related_name='choices', verbose_name='Вопрос')

    class Meta:
        verbose_name = 'Вариант ответа'
        verbose_name_plural = 'Варианты ответов'

    def __str__(self):
        return f'{self.choice_text}'


class Answer(models.Model):
    question = models.ForeignKey('webapp.Poll', on_delete=models.CASCADE, related_name='answers', verbose_name='Вопрос')
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    choice = models.ForeignKey('webapp.Choice', on_delete=models.CASCADE, related_name='answers',
                               verbose_name='Вариант ответа')

    def __str__(self):
        return f'{self.pk}'

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

webapp/forms.py
from django import forms

from webapp.models import Poll, Choice
from django.forms import widgets


class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = '__all__'
        widgets = {
            'question_text': widgets.Input(attrs={'size': 40}),
        }


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        exclude = ['question']
        widgets = {
            'choice_text': widgets.Input(attrs={'size': 30}),
        }

webapp/views.py
from django.shortcuts import render


def index_view(request):
    return render(request, 'index.html')

webapp/views/answer_views.py
from django.db import IntegrityError
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView

from webapp.models import Poll, Choice, Answer


class AnswerView(TemplateView):
    template_name = 'answer/answer.html'

    def get_context_data(self, **kwargs):
        context = super(AnswerView, self).get_context_data(**kwargs)
        question = get_object_or_404(Poll, pk=self.kwargs.get('pk'))
        context['question'] = question
        context['poll_choices'] = question.choices.all()
        context['poll_count'] = self.get_polls_count()
        context['choices_count'] = self.get_choices_count()
        return context

    def post(self, request, *args, **kwargs):
        Answer.objects.create(question_id=self.kwargs.get('pk'), choice_id=self.request.POST.get('choice_pk'))
        nexttt = request.POST.get('next', '/')
        return redirect(nexttt)

    def get_polls_count(self):
        polls_count = Answer.objects.filter(question_id=self.kwargs.get('pk')).count()
        return polls_count

    def get_choices_count(self):
        choices_count = Answer.objects.filter(question_id=self.kwargs.get('pk')).values('choice_id').annotate(
            choice_count=Count('choice_id'))
        return choices_count

    def get_percentage_of_choices(self):
        pass

webapp/views/choice_views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import ChoiceForm
from webapp.models import Choice, Poll


class PollChoiceAddView(CreateView):
    form_class = ChoiceForm
    template_name = 'choice/create.html'
    model = Choice

    def form_valid(self, form):
        question = get_object_or_404(Poll, pk=self.kwargs.get("pk"))
        form.instance.question = question
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("poll_detail_view", kwargs={"pk": self.object.question.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = get_object_or_404(Poll, pk=self.kwargs.get("pk"))
        context['question'] = question
        return context


class PollChoiceUpdate(UpdateView):
    form_class = ChoiceForm
    template_name = 'choice/update.html'
    model = Choice

    def get_success_url(self):
        return reverse("poll_detail_view", kwargs={"pk": self.object.question.pk})


class PollChoiceDelete(DeleteView):
    template_name = 'choice/delete.html'
    model = Choice

    def get_success_url(self):
        return reverse("poll_detail_view", kwargs={"pk": self.object.question.pk})

webapp/views/poll_views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin

from webapp.forms import PollForm, ChoiceForm
from webapp.models import Poll


class PollsIndexView(ListView):
    template_name = 'poll/index.html'
    model = Poll
    ordering = ['-created_at']
    paginate_by = 5


class PollDetailView(FormMixin, DetailView):
    template_name = 'poll/detail.html'
    model = Poll
    form_class = ChoiceForm

    def get_context_data(self, **kwargs):
        context = super(PollDetailView, self).get_context_data(**kwargs)
        poll_choices = self.object.choices.all()
        context['poll_choices'] = poll_choices
        return context


class PollAddView(CreateView):
    template_name = 'poll/create.html'
    form_class = PollForm
    model = Poll


class PollUpdateView(UpdateView):
    template_name = 'poll/update.html'
    form_class = PollForm
    model = Poll


class PollDeleteView(DeleteView):
    template_name = 'poll/delete.html'
    model = Poll
    success_url = reverse_lazy('index')

webapp/templates/answer/answer.html
{% extends 'base.html' %}

{% block title %}Ответить на вопрос{% endblock %}

{% block add-poll-nav %}{% endblock %}

{% block content %}
    {% if poll_choices %}
        <div class="alert alert-success mt-3" role="alert">
            {{ question.question_text }} (ответили: {{ poll_count }} раз)
        </div>
        <form action="{% url 'answer_poll' question.pk %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            {% for choice in poll_choices %}
                <div class="form-check">
                    <input required class="form-check-input" type="radio" value="{{ choice.pk }}" name="choice_pk">
                    <label class="form-check-label" for="answer">
                        {{ choice }} (выбран: {{ x }} раз)
                    </label>
                </div>
            {% endfor %}
            <br>
            <button type="submit" class="btn btn-info">Ответить</button>
        </form>
    {% else %}
        <br>
        <h3>У данного опроса пока нет вариантов для ответа</h3>
    {% endif %}
{% endblock %}

webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'index' %}" class="nav-link px-2 text-white">Главная</a></li>
                {% block add-poll-nav %}
                <li><a href="{% url 'poll_add' %}" class="nav-link px-2 text-white">Добавить вопрос</a></li>
                {% endblock %}
                {% block add-choice-nav %}{% endblock %}
            </ul>
        </div>
    </div>
</header>

<div class="container">
    <div class="container">{% block content %}{% endblock %}</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous">
</script>

<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })
</script>
</body>
</html>

webapp/templates/choice/create.html
{% extends 'base.html' %}

{% block title %}Добавление ответа{% endblock %}

{% block content %}
    <br>
    <h3>{{ question }}</h3>
    <br>
    <form method="post">
        {% include 'partial/form.html' with button_text='Добавить' %}
    </form>
{% endblock %}

webapp/templates/choice/delete.html
{% extends 'base.html' %}

{% block title %}Удаление ответа{% endblock %}

{% block content %}
    <div class="container">
        <h2>Вы уверены что хотите удалить этот ответ: <br> <i>{{ choice.choice_text }}</i></h2>
        <form action="{% url 'poll_choice_delete' choice.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-info">Удалить</button>
            <br>
            <br>
            <p><a class="btn btn-info" href="{% url "poll_detail_view" choice.question.pk %}">Не удалять</a></p>
        </form>
    </div>
{% endblock %}

webapp/templates/choice/update.html
{% extends 'base.html' %}

{% block title %}Изменение ответа{% endblock %}

{% block content %}
        <form method="post">
            {% include "partial/form.html" with button_text="Изменить"  %}
        </form>
{% endblock %}

webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
   <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <div class="mb-3">
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    {{ field }}
    </div>
{% endfor %}

<br>
<input class="btn btn-info" type="submit" value={{ button_text }} />

webapp/templates/partial/pagination.html
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" data-bs-toggle="tooltip" data-bs-placement="top" title="В начало"
                   href="?page=1{% if search %}&search={{ search }}{% endif %}">
                    <span>&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link"
            href="?page={{ page_obj.previous_page_number }}{% if search %}&search={{ search }}{% endif %}">Назад</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Назад</span>
            </li>
        {% endif %}
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.previous_page_number }}{% if search %}&search={{ search }}{% endif %}">
                    {{ page_obj.previous_page_number }}</a>
            </li>
        {% endif %}
        {% if page_obj.number %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">{{ page_obj.number }}</span>
            </li>
        {% endif %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link"
            href="?page={{ page_obj.next_page_number }}{% if search %}&search={{ search }}{% endif %}">
                {{ page_obj.next_page_number }}</a>
            </li>
        {% endif %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link"
            href="?page={{ page_obj.next_page_number }}{% if search %}&search={{ search }}{% endif %}">Далее</a>
            </li>
            <li class="page-item">
                <a class="page-link" data-bs-toggle="tooltip" data-bs-placement="top" title="В конец"
                   href="?page={{ page_obj.paginator.num_pages }}{% if search %}&search={{ search }}{% endif %}">
                    <span>&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Далее</span>
            </li>
        {% endif %}
    </ul>
</nav>

webapp/templates/poll/create.html
{% extends 'base.html' %}

{% block title %}Добавление вопроса{% endblock %}

{% block add-poll-nav %}{% endblock %}

{% block content %}
    <br>
    <form method="post">
        {% include 'partial/form.html' with button_text='Добавить' %}
    </form>
{% endblock %}

webapp/templates/poll/delete.html
{% extends 'base.html' %}

{% block title %}Удаление вопроса{% endblock %}

{% block content %}
    <div class="container">
        <h2>Вы уверены что хотите удалить этот вопрос: <br> <i>{{ poll.question_text }}</i></h2>
        <form action="{% url 'poll_delete' poll.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-info">Удалить</button>
            <br>
            <br>
            <p><a class="btn btn-info" href="{% url "poll_detail_view" poll.pk %}">Не удалять</a></p>
        </form>
    </div>
{% endblock %}

webapp/templates/poll/detail.html
{% extends 'base.html' %}

{% block title %}Вопрос{% endblock %}

{% block add-choice-nav %}
    <li><a href="{% url 'poll_choice_add' poll.pk %}" class="nav-link px-2 text-white">Добавить ответ</a></li>
{% endblock %}

{% block content %}

    <div class="card mt-3">
        <div class="card-header">
            Вопрос
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ poll.question_text }}</h5>
        </div>
        <div class="card-footer text-muted">
            {{ poll.created_at }}
        </div>
    </div>
    <br>
    <a class="btn btn-info" href="{% url 'poll_update' poll.pk %}">Изменить</a>
    <a class="btn btn-info" href="{% url 'poll_delete' poll.pk %}">Удалить</a>
    <a class="btn btn-info" href="{% url 'answer_poll' poll.pk %}">Ответить</a>

    {% if poll_choices %}
        <br><br>
        <h3>Варианты ответа:</h3>
        <ol class="list-group list-group-numbered">
            {% for choice in poll_choices %}
                <li class="list-group-item">{{ choice.choice_text }}</li>
                <div class="d-flex justify-content-start">
                <div><a class="btn btn-warning" href="{% url 'poll_choice_update' choice.pk %}">Редактировать</a></div>
                    &nbsp;
                <div><a class="btn btn-warning" href="{% url 'poll_choice_delete' choice.pk %}">Удалить</a></div>
                </div>
            {% endfor %}
        </ol>
    {% else %}
        <br><br>
        <h3>У данного вопроса пока нет вариантов ответа</h3>
    {% endif %}

{% endblock %}

webapp/templates/poll/index.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}

    <div class="list-group mt-3">
        <h2>Вопросы</h2>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        {% for poll in  poll_list %}
            <a href="{{ poll.get_absolute_url }}"
               class="list-group-item list-group-item-info">{{ poll.question_text.title }}</a>
            <a class="btn btn-info" href="{% url 'answer_poll' poll.pk %}">Пройти опрос</a>
        {% endfor %}
        <br>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}

    </div>

{% endblock %}

webapp/templates/poll/update.html
{% extends 'base.html' %}

{% block title %}Редактирование вопроса{% endblock %}

{% block content %}
    <h2>Редактирование проекта</h2>
    <form method="post">
        {% include "partial/form.html" with button_text="Изменить" %}
    </form>
    <br>
    <a class="btn btn-info" href="{% url 'poll_detail_view' poll.pk %}">Не изменять</a>
{% endblock %}